[option]
database_url = "mongodb://admin:paps123@110.165.16.135:27017/?authSource=admin"
; database_url = "mongodb://admin:paps123@127.0.0.1:27017/?authSource=admin"
database_name = "paps"
server_port = "8000"
; upload_path = "/var/www/uploads/excel"
upload_path = "./uploads"

