[option]
database_url = "mongodb://110.165.16.135:27017/"
database_name = "digitalpaps_test
server_port = "8080"
upload_path = "./uploads"

; 이메일 정보
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "sunziro03@gmail.com"
sender_password = "fabx wcbo lhai fvsn"